name: tabflutter
description: "Demonstrates how to use the flutter_quill package."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_quill: ^11.0.0-dev.4
  flutter_quill_delta_from_html: ^1.4.2
  flutter_quill_extensions: ^11.0.0-dev.3
  math_expressions: ^2.6.0
  path: ^1.9.0
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_quill_test: ^11.0.0-dev.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
